@rootAPI = http://localhost:8000/api/v1/users
@bookAPI = http://localhost:8000/api/v1/books

@reviewAPI = http://localhost:8000/api/v1/reviews

# ======= admin user 
### create new admin user
POST {{rootAPI}}/admin-user
Content-Type: application/json

{
  "fName": "Prem",  
  "lName": "Ach",  
  "phone": "04567890",  
  "email": "ase@a.com",  
  "password": "12345"
}
### Login user
POST {{rootAPI}}/login
Content-Type: application/json

{
  "email": "a@a.com",  
  "password": "12345"
}

### request new accessJWT for  user
GET {{rootAPI}}/get-accessjwt
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE3MDE3MzU0MjEsImV4cCI6MTcwNDMyNzQyMX0.1S5F6vUbpmcVmcIWQXL5LoPKEH3a0XkosGaRXdLD8TE


# ======= student user 
### get students profile
GET  {{rootAPI}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZUBhLmNvbSIsImlhdCI6MTcwMTY1OTEyMSwiZXhwIjoxNzAxNjYwMDIxfQ.AqpXaGTRGnfJ_qffSWjN6sXy3L0A8Ky38Tzd4kUYV7M


### create new students account
POST  {{rootAPI}}

### get all users
GET   {{rootAPI}}/all-users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE3MDI4NTQ3NjgsImV4cCI6MTcwMjg1NTY2OH0.RFzmyP0RuBydErhZgVzxMW5EUiPLzQHzY78GEYRWdnE


# ============== book api 


###Get all the books 
GET {{bookAPI}}

###Get a  book
GET {{bookAPI}}/656eae348fcc3b37a66d4327


### post new book
POST {{bookAPI}}
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE3MDE3NTIwNjAsImV4cCI6MTcwMTc1Mjk2MH0.fZN2qciH-PpTMAlKixozArxr9E6JffzNDcFFWkpXYmQ

{
   "thumbnail": "https://m.media-amazon.com/images/I/51-5ZXYtcML.jpg",
    "name": "Eloquent Javascript",
    "author": "Marijn Haverbeke",
    "publishYear": 2011,
    "isbn": "ui97813523493272821",
    "description": "JavaScript lies at the heart of almost every modern web application, from social apps like Twitter to browser-based game frameworks like Phaser and Babylon. Though simple for beginners to pick up and play with, JavaScript is a flexible, complex language that you can use to build full-scale applications. This much anticipated and thoroughly revised third edition of Eloquent JavaScript dives deep into the JavaScript language to show you how to write beautiful, effective code. It has been updated to reflect the current state of Java¬Script and web browsers and includes brand-new material on features like class notation, arrow functions, iterators, async functions, template strings, and block scope. A host of new exercises have also been added to test your skills and keep you on track. As w..."
}

#============ review api
###
GET {{reviewAPI}}
